#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from commands.collab.engine.registry_constants import (  # noqa: E402
    ALLOWED_COMPLETION_SUBSTATES,
    AUTO_ADVANCE_EXEMPT_PHASES,
    CONVERGENT_REVIEWER_PHASES,
    CREATED_AT_REQUIRED_COLLAB_FIELDS,
    CREATED_AT_REQUIRED_REVIEWER_FIELDS,
    CREATED_AT_REQUIRED_VERIFICATION_FIELDS,
    DEFAULT_OPEN_ROSTER_EFFORT,
    DEFAULT_REVIEWER_MODE,
    DEFAULT_REVIEWER_OPTIONAL_PHASES,
    MOD_EXCLUDED_PHASES,
    ONE_SPEAK_PHASES,
    PHASES,
)


CONFIG_ROOT = Path(os.environ.get('COMMAND_CONFIG_ROOT', ROOT)).expanduser().resolve()
ARTIFACT = CONFIG_ROOT / 'generated' / 'collab-lifecycle.md'


def yes_no(value: bool) -> str:
    return 'yes' if value else 'no'


def speak_rule(phase: str) -> str:
    if phase in ONE_SPEAK_PHASES:
        return 'one contribution per required role'
    if phase == 'Discussion':
        return 'open discussion turns'
    if phase == 'Completion':
        return 'execution records, then reviewer seal when configured'
    return 'phase-specific'


def reviewer_rule(phase: str) -> str:
    if phase in CONVERGENT_REVIEWER_PHASES:
        return 'required last in convergent reviewer mode'
    if phase in DEFAULT_REVIEWER_OPTIONAL_PHASES:
        return 'optional'
    return 'none'


def phase_rows() -> list[str]:
    rows = [
        '| Phase | Speak rule | Auto-advance exempt | Moderator excluded | Reviewer rule |',
        '| --- | --- | --- | --- | --- |',
    ]
    for phase in PHASES:
        rows.append(
            '| {phase} | {speak} | {auto} | {moderator} | {reviewer} |'.format(
                phase=phase,
                speak=speak_rule(phase),
                auto=yes_no(phase in AUTO_ADVANCE_EXEMPT_PHASES),
                moderator=yes_no(phase in MOD_EXCLUDED_PHASES),
                reviewer=reviewer_rule(phase),
            )
        )
    return rows


def glossary_rows() -> list[str]:
    entries = [
        (
            'activePhase',
            'Current lifecycle phase. Valid values are imported from `PHASES`.',
        ),
        (
            'completion.subState',
            'Reviewer-backed Completion sub-state: '
            + ', '.join(f'`{item}`' for item in sorted(ALLOWED_COMPLETION_SUBSTATES))
            + '.',
        ),
        (
            'turnOrder',
            'Ordered speaker cycle for ordinary roles; reviewer roles are excluded in convergent reviewer mode.',
        ),
        (
            'moderatorRole',
            'Participant that starts the collab and is removed from later implementation phases.',
        ),
        (
            'reviewerRole',
            'Optional reviewer that speaks last in convergent phases when configured.',
        ),
        (
            'reviewerMode',
            'Stamped reviewer behavior mode for records with `createdAt`; default is '
            f'`{DEFAULT_REVIEWER_MODE}`.',
        ),
        (
            'reviewerOptionalPhases',
            'Stamped phases where the reviewer may speak without blocking the ordinary expected speaker; '
            f'default is {", ".join(f"`{phase}`" for phase in DEFAULT_REVIEWER_OPTIONAL_PHASES)}.',
        ),
        (
            'open-roster effort',
            f'Fallback effort level for joined roles absent from the effort matrix; default is `{DEFAULT_OPEN_ROSTER_EFFORT}`.',
        ),
        (
            'createdAt required fields',
            'Records with `createdAt` must declare '
            f'{", ".join(f"`{field}`" for field in CREATED_AT_REQUIRED_COLLAB_FIELDS)}; '
            'reviewer-backed records must also declare '
            f'{", ".join(f"`{field}`" for field in CREATED_AT_REQUIRED_REVIEWER_FIELDS)}; '
            'verification records must declare '
            f'{", ".join(f"`verification.{field}`" for field in CREATED_AT_REQUIRED_VERIFICATION_FIELDS)}.',
        ),
        (
            'execution.<role>',
            'Completion metadata for each executing role: status, date, validation result, and touched paths.',
        ),
        (
            'verification.rounds',
            'Registry-counted reviewer/executor paired events in `Completion.verification`.',
        ),
        (
            'verificationSeal',
            'Reviewer seal object that binds observed registry revision, execution entries, validation scopes, and touched paths.',
        ),
        (
            'activeCollabId',
            'Registry pointer for the selected open collaboration record.',
        ),
    ]
    rows = [
        '| Field | Meaning |',
        '| --- | --- |',
    ]
    rows.extend(f'| `{field}` | {meaning} |' for field, meaning in entries)
    return rows


def render() -> str:
    lines = [
        '# Collab Lifecycle',
        '',
        '_Generated by `commands/collab/engine/lifecycle-doc.py`; do not edit this file by hand._',
        '',
        'This reference orients agents to the registry-backed collab lifecycle. The phase data is imported from `commands/collab/engine/registry.py` constants.',
        '',
        '## Phase Table',
        '',
        *phase_rows(),
        '',
        '## Field Glossary',
        '',
        *glossary_rows(),
        '',
        '## Source Of Truth',
        '',
        'Source-of-truth pattern: constant import. The generator imports lifecycle constants directly from `commands/collab/engine/registry.py` and renders this artifact without reading working-directory state, environment variables, locale settings, timestamps, or filesystem scan order.',
        '',
    ]
    return '\n'.join(lines)


def write_artifact() -> None:
    ARTIFACT.parent.mkdir(parents=True, exist_ok=True)
    with ARTIFACT.open('w', encoding='utf-8', newline='\n') as handle:
        handle.write(render())


def check_artifact() -> int:
    expected = render()
    if not ARTIFACT.exists():
        print(
            'collab-lifecycle: missing generated artifact; run `commands/collab/engine/lifecycle-doc.py --render` to update',
            file=sys.stderr,
        )
        return 1
    actual = ARTIFACT.read_text(encoding='utf-8')
    if actual != expected:
        diff = ''.join(
            difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(ARTIFACT),
                tofile='rendered',
            )
        )
        print(
            'collab-lifecycle: generated artifact is stale; run `commands/collab/engine/lifecycle-doc.py --render` to update',
            file=sys.stderr,
        )
        print(diff, file=sys.stderr, end='')
        return 1
    print('collab-lifecycle: OK')
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description='Render or validate the generated collab lifecycle reference.')
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--render', action='store_true', help='write generated/collab-lifecycle.md')
    mode.add_argument('--check', action='store_true', help='verify generated/collab-lifecycle.md is current')
    args = parser.parse_args()
    if args.render:
        write_artifact()
        print(f'collab-lifecycle: rendered {ARTIFACT.relative_to(ROOT)}')
        return 0
    return check_artifact()


if __name__ == '__main__':
    raise SystemExit(main())
