#!/usr/bin/env python3
"""Argparse surface and generated CLI documentation for registry.py."""
from __future__ import annotations

import argparse
from pathlib import Path

from commands.collab.engine.config_paths import (
    DEFAULT_AGENT_MODEL_PATH,
    DEFAULT_EFFORT_PATH,
    DEFAULT_FLAG_TAXONOMY_PATH,
    DEFAULT_ROLES_DIR,
)
from commands.collab.engine.parser_introspection import (
    action_display_name,
    action_value_shape,
    parser_subcommands,
)
from commands.collab.engine.registry_constants import (
    ALLOWED_EXECUTION_STATUSES,
    ALLOWED_STATUSES,
    ALLOWED_VALIDATION_SCOPES,
    PHASES,
)

ROOT = Path(__file__).resolve().parents[3]


def render_registry_cli_doc() -> str:
    parser = build_parser()
    subcommands = parser_subcommands(parser)
    lines = [
        '# Registry CLI',
        '',
        '_Generated by `commands/collab/engine/registry.py registry-cli-doc`; do not edit by hand._',
        '',
        '## Global options',
        '',
        '- `--registry <path>` optional; bypasses the project-id state resolver.',
        '',
        '## Subcommands',
        '',
    ]
    for name in sorted(subcommands):
        subparser = subcommands[name]
        usage = subparser.format_usage().strip()
        if usage.startswith('usage: '):
            usage = usage[len('usage: '):]
        lines.extend([f'### `{name}`', '', f'Usage: `{usage}`', ''])
        actions = [
            action for action in subparser._actions
            if action.dest != 'help' and action.default is not argparse.SUPPRESS
        ]
        if actions:
            lines.append('Arguments and flags:')
            for action in actions:
                if action.option_strings:
                    required = 'required' if getattr(action, 'required', False) else 'optional'
                else:
                    required = 'optional' if action.nargs == '?' else 'required'
                lines.append(
                    f'- `{action_display_name(action)}` {required}; {action_value_shape(action)}'
                )
            lines.append('')
        else:
            lines.extend(['Arguments and flags: none', ''])
    return '\n'.join(lines).rstrip() + '\n'


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description='Shared collab registry helper.')
    parser.add_argument(
        '--registry',
        default=None,
        help='Path to the collab registry JSON file; bypasses the project-id state resolver.',
    )
    subparsers = parser.add_subparsers(dest='command', required=True)

    subparsers.add_parser('validate')
    subparsers.add_parser('registry-path')
    registry_cli_doc_parser = subparsers.add_parser('registry-cli-doc')
    registry_cli_doc_parser.add_argument('--check', action='store_true')
    list_parser = subparsers.add_parser('list')
    list_parser.add_argument('--status', choices=sorted(ALLOWED_STATUSES))
    log_parser = subparsers.add_parser('log')
    log_parser.add_argument('target')
    flag_inventory_parser = subparsers.add_parser('flag-inventory')
    flag_inventory_parser.add_argument('--spec', default=str(DEFAULT_FLAG_TAXONOMY_PATH))
    help_parser = subparsers.add_parser('help')
    help_parser.add_argument('route', nargs='*')
    subparsers.add_parser('timestamp')
    subparsers.add_parser('banner-timestamp')

    role_row_parser = subparsers.add_parser('role-row')
    role_row_parser.add_argument('role')
    role_row_parser.add_argument('--roles-dir', default=str(DEFAULT_ROLES_DIR))
    role_row_parser.add_argument('--index', type=int, default=1)

    roles_parser = subparsers.add_parser('roles')
    roles_parser.add_argument('--roles-dir', default=str(DEFAULT_ROLES_DIR))

    summary_role_parser = subparsers.add_parser('summary-role')
    summary_role_parser.add_argument('line')

    reviewer_state_parser = subparsers.add_parser('reviewer-state')
    reviewer_state_parser.add_argument('target')

    handoff_state_parser = subparsers.add_parser('handoff-state')
    handoff_state_parser.add_argument('target')
    handoff_state_parser.add_argument('role')

    activate_parser = subparsers.add_parser('activate')
    activate_parser.add_argument('target')

    open_parser = subparsers.add_parser('open')
    open_parser.add_argument('target')
    open_parser.add_argument('--caller-role')

    init_parser = subparsers.add_parser(
        'init',
        usage=(
            '%(prog)s --agent-id <agentId> [--reviewer <role>] '
            '[--terminal <seal|issue>] [--no-participant-verification] [--work-repo <path>] [--open] <name>'
        ),
        description='Create a registry-backed collab record.',
    )
    init_parser.add_argument('--agent-id', action='append')
    init_parser.add_argument('--reviewer', action='append')
    init_parser.add_argument('--terminal', action='append')
    init_parser.add_argument('--work-repo', action='append')
    init_parser.add_argument('--no-participant-verification', dest='participant_verification', action='store_false', default=True)
    init_parser.add_argument('--open', action='store_true')
    init_parser.add_argument('name', nargs='*')

    join_participants_parser = subparsers.add_parser('join-participants')
    join_participants_parser.add_argument('target')
    join_participants_parser.add_argument('role')
    join_participants_parser.add_argument('--agent-id', required=True)
    join_participants_parser.add_argument('--roles-dir', default=str(DEFAULT_ROLES_DIR))
    join_participants_parser.add_argument('--json', action='store_true')

    remove_participant_parser = subparsers.add_parser('remove-participant')
    remove_participant_parser.add_argument('target')
    remove_participant_parser.add_argument('role')
    remove_participant_parser.add_argument('--roles-dir', default=str(DEFAULT_ROLES_DIR))
    remove_participant_parser.add_argument('--caller-role')

    set_parser = subparsers.add_parser('set')
    set_parser.add_argument('target')
    set_parser.add_argument('field')
    set_parser.add_argument('value', nargs='?')
    set_parser.add_argument('--force', action='store_true')
    set_parser.add_argument('--clear', action='store_true')
    set_parser.add_argument('--roles-dir', default=str(DEFAULT_ROLES_DIR))
    set_parser.add_argument('--caller-role')

    unset_parser = subparsers.add_parser('unset')
    unset_parser.add_argument('target')
    unset_parser.add_argument('field')
    unset_parser.add_argument('--roles-dir', default=str(DEFAULT_ROLES_DIR))
    unset_parser.add_argument('--caller-role')

    effort_state_parser = subparsers.add_parser('effort-state')
    effort_state_parser.add_argument('target')
    effort_state_parser.add_argument('role')
    effort_state_parser.add_argument('--effort-defaults', default=str(DEFAULT_EFFORT_PATH))

    audit_effort_matrix_parser = subparsers.add_parser('audit-effort-matrix')
    audit_effort_matrix_parser.add_argument('--effort-defaults', default=str(DEFAULT_EFFORT_PATH))
    audit_effort_matrix_parser.add_argument('--agent-model', default=str(DEFAULT_AGENT_MODEL_PATH))

    advance_parser = subparsers.add_parser('advance')
    advance_parser.add_argument('target')
    advance_parser.add_argument('direction', choices=['next', 'prev'])
    advance_parser.add_argument('--json', action='store_true')
    advance_parser.add_argument('--caller-role')

    restore_parser = subparsers.add_parser('restore')
    restore_parser.add_argument('target')
    restore_parser.add_argument('--to', required=True)
    restore_parser.add_argument('--caller-role')

    speak_parser = subparsers.add_parser('speak-lifecycle')
    speak_parser.add_argument('target')
    speak_parser.add_argument('contributors', nargs='+')

    speak_state_parser = subparsers.add_parser('speak-state')
    speak_state_parser.add_argument('target')
    speak_state_parser.add_argument('role')
    speak_state_parser.add_argument('--resume', action='store_true')

    speak_live_parser = subparsers.add_parser('speak-lifecycle-live')
    speak_live_parser.add_argument('target')

    speak_render_parser = subparsers.add_parser('speak-render')
    speak_render_parser.add_argument('target')
    speak_render_parser.add_argument('role')
    speak_render_parser.add_argument('--content-file', required=True)
    speak_render_parser.add_argument('--full-body-file')
    speak_render_parser.add_argument('--observed-revision', type=int, required=True)
    speak_render_parser.add_argument('--timestamp')
    speak_render_parser.add_argument('--json', action='store_true')
    speak_render_parser.add_argument('--caller-role')
    speak_render_parser.add_argument('--verbatim', action='store_true')

    re_speak_render_parser = subparsers.add_parser('rewrite-speak-render')
    re_speak_render_parser.add_argument('target')
    re_speak_render_parser.add_argument('role')
    re_speak_render_parser.add_argument('--content-file', required=True)
    re_speak_render_parser.add_argument('--full-body-file')
    re_speak_render_parser.add_argument('--timestamp')
    re_speak_render_parser.add_argument('--caller-role')
    re_speak_render_parser.add_argument('--verbatim', action='store_true')

    retract_speak_parser = subparsers.add_parser('retract-speak')
    retract_speak_parser.add_argument('target')
    retract_speak_parser.add_argument('role')
    retract_speak_parser.add_argument('--reason')
    retract_speak_parser.add_argument('--timestamp')
    retract_speak_parser.add_argument('--caller-role')

    execution_parser = subparsers.add_parser('execution')
    execution_parser.add_argument('target')
    execution_parser.add_argument('role')
    execution_parser.add_argument('status', choices=sorted(ALLOWED_EXECUTION_STATUSES))
    execution_parser.add_argument('date')
    execution_parser.add_argument('--assigned-role', action='append', default=[])
    execution_parser.add_argument('--auto-close', action='store_true')
    execution_parser.add_argument('--validation-result')
    execution_parser.add_argument('--validation-scope', choices=sorted(ALLOWED_VALIDATION_SCOPES))
    execution_parser.add_argument('--touched-path', action='append', default=[])
    execution_parser.add_argument('--agent-id')
    execution_parser.add_argument('--json', action='store_true')
    execution_parser.add_argument('--caller-role')

    export_issues_parser = subparsers.add_parser('export-issues')
    export_issues_parser.add_argument('target')
    export_issues_parser.add_argument('role')
    export_issues_parser.add_argument('--evidence-file', required=True)
    export_issues_parser.add_argument('--timestamp')
    export_issues_parser.add_argument('--json', action='store_true')
    export_issues_parser.add_argument('--caller-role')

    repair_execution_parser = subparsers.add_parser('repair-execution-provenance')
    repair_execution_parser.add_argument('target')
    repair_execution_parser.add_argument('role')
    repair_execution_parser.add_argument('--work-repo')
    repair_execution_parser.add_argument('--commit', action='append', default=[])
    repair_execution_parser.add_argument('--caller-role')

    tag_parser = subparsers.add_parser('tag')
    tag_parser.add_argument('target', nargs='?')
    tag_parser.add_argument('--tag', dest='tag_name')
    tag_parser.add_argument('--confirm', action='store_true')
    tag_parser.add_argument('--push', action='store_true')
    tag_parser.add_argument('--caller-role')

    release_parser = subparsers.add_parser('release')
    release_parser.add_argument('target', nargs='?')
    release_parser.add_argument('--tag', dest='tag_name')
    release_parser.add_argument('--confirm', action='store_true')
    release_parser.add_argument('--push', action='store_true')
    release_parser.add_argument('--direct-merge', action='store_true')
    release_parser.add_argument('--github-release', action='store_true')
    release_parser.add_argument('--auto-fire', action='store_true')
    release_parser.add_argument('--caller-role')

    execute_spawn_parser = subparsers.add_parser('execute-spawn')
    execute_spawn_parser.add_argument('target')
    execute_spawn_parser.add_argument('role')
    execute_spawn_parser.add_argument('--scope', required=True)
    execute_spawn_parser.add_argument('--sibling-scope', action='append', default=[])
    execute_spawn_parser.add_argument('--returned-path', action='append', default=[])

    transcript_repair_parser = subparsers.add_parser('transcript-repair')
    transcript_repair_parser.add_argument('target')
    transcript_repair_parser.add_argument('--touch-execution-evidence', action='store_true')
    transcript_repair_parser.add_argument('--caller-role')

    out_of_scope_patch_parser = subparsers.add_parser('out-of-scope-patch')
    out_of_scope_patch_parser.add_argument('target')
    out_of_scope_patch_parser.add_argument('role')
    out_of_scope_patch_parser.add_argument('--path', required=True)
    out_of_scope_patch_parser.add_argument('--caller-role')

    transcript_view_parser = subparsers.add_parser('transcript-view')
    transcript_view_parser.add_argument('target')
    transcript_view_parser.add_argument('phase', choices=PHASES)
    transcript_view_parser.add_argument('--raw', action='store_true')

    summarize_parser = subparsers.add_parser('summarize')
    summarize_parser.add_argument('target')
    summarize_parser.add_argument('--date')

    participant_verify_state_parser = subparsers.add_parser('participant-verify-state')
    participant_verify_state_parser.add_argument('target')
    participant_verify_state_parser.add_argument('role')
    participant_verify_state_parser.add_argument('--resume', action='store_true')

    participant_verify_render_parser = subparsers.add_parser('participant-verify-render')
    participant_verify_render_parser.add_argument('target')
    participant_verify_render_parser.add_argument('role')
    participant_verify_render_parser.add_argument('--observed-revision', type=int, required=True)
    participant_verify_render_parser.add_argument('--audit-file', required=True)
    participant_verify_render_parser.add_argument('--remediation-file', required=True)
    participant_verify_render_parser.add_argument('--final-audit-file', required=True)
    participant_verify_render_parser.add_argument('--status', choices=['completed', 'failed'], required=True)
    participant_verify_render_parser.add_argument('--touched-path', action='append', default=[])
    participant_verify_render_parser.add_argument('--execution-agent-id')
    participant_verify_render_parser.add_argument('--audit-agent-id')
    participant_verify_render_parser.add_argument('--remediation-agent-id')
    participant_verify_render_parser.add_argument('--timestamp')
    participant_verify_render_parser.add_argument('--caller-role')

    seal_state_parser = subparsers.add_parser('seal-state')
    seal_state_parser.add_argument('target')
    seal_state_parser.add_argument('role', nargs='?')
    seal_state_parser.add_argument('--resume', action='store_true')

    seal_render_parser = subparsers.add_parser('seal-render')
    seal_render_parser.add_argument('target')
    seal_render_parser.add_argument('role')
    seal_render_parser.add_argument('--observed-revision', type=int, required=True)
    seal_render_parser.add_argument('--cap-exit')
    seal_render_parser.add_argument('--outcome')
    seal_render_parser.add_argument('--restore-target')
    seal_render_parser.add_argument('--restore-reason')
    seal_render_parser.add_argument('--evidence')
    seal_render_parser.add_argument('--failure-category')
    seal_render_parser.add_argument('--null-result', action='store_true')
    seal_render_parser.add_argument('--json', action='store_true')
    seal_render_parser.add_argument('--caller-role')

    seal_write_parser = subparsers.add_parser('seal-write')
    seal_write_parser.add_argument('target')
    seal_write_parser.add_argument('role')
    seal_write_parser.add_argument('--observed-revision', type=int, required=True)
    seal_write_parser.add_argument('--cap-exit')
    seal_write_parser.add_argument('--restore-reason')
    seal_write_parser.add_argument('--evidence')
    seal_write_parser.add_argument('--failure-category')
    seal_write_parser.add_argument('--json', action='store_true')
    seal_write_parser.add_argument('--caller-role')

    record_verdict_parser = subparsers.add_parser('record-verdict')
    record_verdict_parser.add_argument('target')
    record_verdict_parser.add_argument('role')
    record_verdict_parser.add_argument('--observed-revision', type=int, required=True)
    record_verdict_parser.add_argument('--outcome', required=True)
    record_verdict_parser.add_argument('--restore-target')
    record_verdict_parser.add_argument('--restore-reason')
    record_verdict_parser.add_argument('--evidence')
    record_verdict_parser.add_argument('--failure-category')
    record_verdict_parser.add_argument('--null-result', action='store_true')
    record_verdict_parser.add_argument('--json', action='store_true')
    record_verdict_parser.add_argument('--caller-role')

    restart_verification_parser = subparsers.add_parser('restart-verification')
    restart_verification_parser.add_argument('target')
    restart_verification_parser.add_argument('--caller-role')

    reopen_parser = subparsers.add_parser('reopen')
    reopen_parser.add_argument('target')
    reopen_parser.add_argument('phase', choices=['action-plan', 'handoff'])
    reopen_parser.add_argument('--caller-role')

    show_verdict_parser = subparsers.add_parser('show-verdict')
    show_verdict_parser.add_argument('target')

    re_summarize_parser = subparsers.add_parser('rewrite-summary')
    re_summarize_parser.add_argument('target')
    re_summarize_parser.add_argument('--summary-file', required=True)
    re_summarize_parser.add_argument('--date')

    close_parser = subparsers.add_parser('close')
    close_parser.add_argument('target')
    close_parser.add_argument('--json', action='store_true')
    close_parser.add_argument('--caller-role')

    subparsers.add_parser('audit-closed')

    archive_parser = subparsers.add_parser('archive')
    archive_parser.add_argument('target')
    archive_parser.add_argument('--json', action='store_true')
    archive_parser.add_argument('--caller-role')

    delete_parser = subparsers.add_parser('delete')
    delete_parser.add_argument('target')
    delete_parser.add_argument('--yes', action='store_true')
    delete_parser.add_argument('--caller-role')

    diff_parser = subparsers.add_parser('diff')
    diff_parser.add_argument('target', nargs='?')

    render_status_parser = subparsers.add_parser('render-status')
    render_status_parser.add_argument('target')

    status_view_parser = subparsers.add_parser('status-view')
    status_view_parser.add_argument('target')

    render_participants_parser = subparsers.add_parser('render-participants')
    render_participants_parser.add_argument('target')
    render_participants_parser.add_argument('--roles-dir', default=str(DEFAULT_ROLES_DIR))

    write_guard_parser = subparsers.add_parser('write-guard')
    write_guard_parser.add_argument('route')
    write_guard_parser.add_argument('paths', nargs='+')

    return parser
