#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
COMMAND_CONFIG_ROOT="${COMMAND_CONFIG_ROOT:-$ROOT}"
CONTRACT="${COMMAND_CONFIG_ROOT}/_core/agent-role.md"
BEGIN_MARKER="<!-- BEGIN GENERATED:ROLES_ROSTER -->"
END_MARKER="<!-- END GENERATED:ROLES_ROSTER -->"
MODE="write"

die() {
  echo "sync-roles-roster: $*" >&2
  exit 1
}

usage() {
  cat <<'USAGE'
Usage: ./tools/command-system/sync-roles-roster.sh [--check]

Options:
  --check  Fail when generated role roster content is stale.
USAGE
}

assert_markers() {
  local begin_count end_count
  begin_count="$(grep -Fc "$BEGIN_MARKER" "$CONTRACT" || true)"
  end_count="$(grep -Fc "$END_MARKER" "$CONTRACT" || true)"
  [[ "$begin_count" == "1" ]] || die "expected exactly one begin marker in ${CONTRACT}"
  [[ "$end_count" == "1" ]] || die "expected exactly one end marker in ${CONTRACT}"
}

extract_existing_block() {
  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" '
    $0 == begin { in_block = 1; next }
    $0 == end { exit }
    in_block { print }
  ' "$CONTRACT"
}

generate_block() {
  printf '%s\n' "_Generated by \`tools/command-system/sync-roles-roster.sh\`; do not edit this block by hand._"
  printf '\n'
  printf '%s\n' "| Key | Display name |"
  printf '%s\n' "|-----|--------------|"
  python3 "$ROOT/tools/command-system/roles.py" --roles-dir "$COMMAND_CONFIG_ROOT/_roles" roster
}

write_block() {
  local generated_file="$1" tmp_file
  tmp_file="$(mktemp)"
  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v generated="$generated_file" '
    $0 == begin {
      print
      while ((getline line < generated) > 0) {
        print line
      }
      in_block = 1
      next
    }
    $0 == end {
      in_block = 0
      print
      next
    }
    !in_block { print }
  ' "$CONTRACT" >"$tmp_file"
  mv "$tmp_file" "$CONTRACT"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      MODE="check"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
  shift
done

[[ -f "$CONTRACT" ]] || die "missing role contract: $CONTRACT"
assert_markers

generated="$(mktemp)"
existing="$(mktemp)"
trap 'rm -f "$generated" "$existing"' EXIT

generate_block >"$generated"
extract_existing_block >"$existing"

if ! cmp -s "$generated" "$existing"; then
  if [[ "$MODE" == "check" ]]; then
    die "generated roster is stale in ${CONTRACT}; run ./tools/command-system/sync-roles-roster.sh"
  fi
  write_block "$generated"
  echo "sync-roles-roster: updated ${CONTRACT}"
  exit 0
fi

if [[ "$MODE" == "check" ]]; then
  echo "sync-roles-roster: OK"
else
  echo "sync-roles-roster: already up to date"
fi
