#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
COMMAND_CONFIG_ROOT="${COMMAND_CONFIG_ROOT:-$ROOT}"
CATALOG="${COMMAND_CONFIG_ROOT}/commands/commands.md"
BEGIN_MARKER="<!-- BEGIN GENERATED:COMMANDS_ROSTER -->"
END_MARKER="<!-- END GENERATED:COMMANDS_ROSTER -->"
MODE="write"

die() {
  echo "sync-commands-catalog: $*" >&2
  exit 1
}

usage() {
  cat <<'USAGE'
Usage: ./tools/command-system/sync-commands-catalog.sh [--check]

Options:
  --check  Fail when generated roster content is stale.
USAGE
}

escape_table_cell() {
  sed 's/|/\\|/g'
}

function_slash() {
  local function_file="$1" slash
  slash="$(sed -n 's/^\*\*Slash:\*\* //p' "$function_file" | head -n 1)"
  if [[ "$slash" == \`*\` ]]; then
    slash="${slash#\`}"
    slash="${slash%\`}"
  fi
  printf '%s' "$slash"
}

route_label() {
  local route_file="$1" ns="$2" route
  route="$(function_slash "$route_file")"
  if [[ -n "$route" && "$route" == "/${ns} "* ]]; then
    route="${route#"/${ns} "}"
  elif [[ -n "$route" && "$route" == "/${ns}" ]]; then
    route="${ns}"
  else
    route="$(basename "$route_file" .md)"
    if [[ "$route" == "index" ]]; then
      route="$(basename "$(dirname "$route_file")")"
    fi
  fi
  printf '%s' "$route"
}

command_rel_path() {
  local command_file="$1" rel base
  rel="${command_file#"${COMMAND_CONFIG_ROOT}/commands/"}"
  base="$(basename "$command_file")"
  if [[ "$base" == "index.md" ]]; then
    printf '%s' "$rel"
  else
    printf '%s' "$base"
  fi
}

assert_markers() {
  local begin_count end_count
  begin_count="$(grep -Fc "$BEGIN_MARKER" "$CATALOG" || true)"
  end_count="$(grep -Fc "$END_MARKER" "$CATALOG" || true)"
  [[ "$begin_count" == "1" ]] || die "expected exactly one begin marker in ${CATALOG}"
  [[ "$end_count" == "1" ]] || die "expected exactly one end marker in ${CATALOG}"
}

extract_existing_block() {
  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" '
    $0 == begin { in_block = 1; next }
    $0 == end { exit }
    in_block { print }
  ' "$CATALOG"
}

generate_block() {
  local command_file rel base ns slash signature signature_cell public_link
  local function_file function_rel route slash_route function_link function_cell
  local function_links
  local -a namespace_functions route_entries command_files

  printf '%s\n' "_Generated by \`tools/command-system/sync-commands-catalog.sh\`; do not edit this block by hand._"
  printf '\n'
  printf '%s\n' "| Slash | Signature | Public router | Private functions |"
  printf '%s\n' "| --- | --- | --- | --- |"

  command_files=()
  while IFS= read -r command_file; do
    command_files+=("$command_file")
  done < <(
    {
      find "${COMMAND_CONFIG_ROOT}/commands" -maxdepth 1 -type f -name '*.md'
      find "${COMMAND_CONFIG_ROOT}/commands" -mindepth 2 -maxdepth 2 -type f -name 'index.md'
    } | sort
  )

  for command_file in "${command_files[@]}"; do
    rel="$(command_rel_path "$command_file")"
    base="$(basename "$command_file")"
    [[ "$base" == "commands.md" ]] && continue

    if [[ "$base" == "index.md" ]]; then
      ns="$(basename "$(dirname "$command_file")")"
    else
      ns="${base%.md}"
    fi
    slash="$(awk '/^# / { print $2; exit }' "$command_file")"
    signature="$(sed -n 's/^\*\*Signature:\*\* //p' "$command_file" | head -n 1)"
    [[ -n "$signature" ]] || signature="$slash"
    if [[ "$signature" == \`*\` ]]; then
      signature="${signature#\`}"
      signature="${signature%\`}"
    fi
    signature_cell="$(printf '%s' "$signature" | escape_table_cell)"
    public_link="[${ns}](${rel})"

    namespace_functions=()
    while IFS= read -r function_file; do
      namespace_functions+=("$function_file")
    done < <(find "${COMMAND_CONFIG_ROOT}/_functions/${ns}" -maxdepth 1 -type f -name '*.md' 2>/dev/null | sort)
    while IFS= read -r function_file; do
      namespace_functions+=("$function_file")
    done < <(find "${COMMAND_CONFIG_ROOT}/commands/${ns}" -mindepth 2 -maxdepth 2 -type f -name 'index.md' 2>/dev/null | sort)

    if ((${#namespace_functions[@]} == 0)); then
      function_cell="n/a"
    else
      function_links=""
      for function_file in "${namespace_functions[@]}"; do
        route="$(route_label "$function_file" "$ns")"
        if [[ "$function_file" == "${COMMAND_CONFIG_ROOT}/_functions/"* ]]; then
          function_rel="${function_file#"${COMMAND_CONFIG_ROOT}/_functions/"}"
          function_link="[${route}](../_functions/${function_rel})"
        else
          function_rel="${function_file#"${COMMAND_CONFIG_ROOT}/commands/"}"
          function_link="[${route}](${function_rel})"
        fi
        if [[ -n "$function_links" ]]; then
          function_links="${function_links}, "
        fi
        function_links="${function_links}${function_link}"
      done
      function_cell="$function_links"
    fi

    printf "| \`%s\` | \`%s\` | %s | %s |\n" "$slash" "$signature_cell" "$public_link" "$function_cell"
  done

  printf '\n'
  printf '%s\n' "| Route | Private function |"
  printf '%s\n' "| --- | --- |"
  route_entries=()
  while IFS= read -r function_file; do
    route_entries+=("$function_file")
  done < <(
    {
      find "${COMMAND_CONFIG_ROOT}/_functions" -type f -name '*.md'
      find "${COMMAND_CONFIG_ROOT}/commands" -mindepth 3 -maxdepth 3 -type f -name 'index.md'
    } | sort
  )
  for function_file in "${route_entries[@]}"; do
    if [[ "$function_file" == "${COMMAND_CONFIG_ROOT}/_functions/"* ]]; then
      function_rel="${function_file#"${COMMAND_CONFIG_ROOT}/_functions/"}"
      ns="$(dirname "$function_rel")"
      function_link="[${function_rel}](../_functions/${function_rel})"
    else
      function_rel="${function_file#"${COMMAND_CONFIG_ROOT}/commands/"}"
      ns="$(dirname "$(dirname "$function_rel")")"
      function_link="[${function_rel}](${function_rel})"
    fi
    route="$(route_label "$function_file" "$ns")"
    slash_route="$(function_slash "$function_file")"
    if [[ -z "$slash_route" ]]; then
      slash_route="/${ns} ${route}"
      if [[ "$ns" == "test" && "$route" == "run" ]]; then
        slash_route="/test"
      fi
    fi
    function_cell="$(printf '%s' "$slash_route" | escape_table_cell)"
    printf "| \`%s\` | %s |\n" "$function_cell" "$function_link"
  done
}

write_block() {
  local generated_file="$1" tmp_file
  tmp_file="$(mktemp)"
  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v generated="$generated_file" '
    $0 == begin {
      print
      while ((getline line < generated) > 0) {
        print line
      }
      in_block = 1
      next
    }
    $0 == end {
      in_block = 0
      print
      next
    }
    !in_block { print }
  ' "$CATALOG" >"$tmp_file"
  mv "$tmp_file" "$CATALOG"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      MODE="check"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
  shift
done

[[ -f "$CATALOG" ]] || die "missing catalog: $CATALOG"
assert_markers

generated="$(mktemp)"
existing="$(mktemp)"
trap 'rm -f "$generated" "$existing"' EXIT

generate_block >"$generated"
extract_existing_block >"$existing"

if ! cmp -s "$generated" "$existing"; then
  if [[ "$MODE" == "check" ]]; then
    die "generated roster is stale in ${CATALOG}; run ./tools/command-system/sync-commands-catalog.sh"
  fi
  write_block "$generated"
  echo "sync-commands-catalog: updated ${CATALOG}"
  exit 0
fi

if [[ "$MODE" == "check" ]]; then
  echo "sync-commands-catalog: OK"
else
  echo "sync-commands-catalog: already up to date"
fi
