#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
COMMAND_CONFIG_ROOT="${COMMAND_CONFIG_ROOT:-$ROOT}"
CONTRACT="${COMMAND_CONFIG_ROOT}/_core/framework-boundaries.md"
BEGIN_MARKER="<!-- BEGIN GENERATED:FRAMEWORK_BOUNDARIES -->"
END_MARKER="<!-- END GENERATED:FRAMEWORK_BOUNDARIES -->"
MODE="write"

die() {
  echo "sync-framework-boundaries: $*" >&2
  exit 1
}

usage() {
  cat <<'USAGE'
Usage: ./tools/command-system/sync-framework-boundaries.sh [--check]

Options:
  --check  Fail when generated framework-boundary content is stale.
USAGE
}

has_any() {
  local dir="$1"
  shift
  [[ -d "$dir" ]] || return 1
  [[ -n "$(find "$dir" "$@" -print -quit)" ]]
}

has_public_commands() {
  has_any "${COMMAND_CONFIG_ROOT}/commands" -maxdepth 1 -type f -name '*.md' ! -name 'commands.md'
}

has_private_functions() {
  has_any "${COMMAND_CONFIG_ROOT}/_functions" -type f -name '*.md'
}

status_instructions() {
  if [[ -f "$ROOT/AGENTS.md" && -f "$ROOT/CLAUDE.md" \
    && -d "${COMMAND_CONFIG_ROOT}/_core" && -f "${COMMAND_CONFIG_ROOT}/commands/commands.md" ]]; then
    printf '%s' "present"
  else
    printf '%s' "absent"
  fi
}

status_workflows() {
  if has_public_commands && has_private_functions; then
    printf '%s' "present"
  else
    printf '%s' "absent"
  fi
}

status_repo_tools() {
  if has_any "$ROOT/tools" -type f \( -name '*.sh' -o -name '*.py' \); then
    printf '%s' "present"
  else
    printf '%s' "absent"
  fi
}

status_adapters() {
  if [[ -f "$ROOT/AGENTS.md" && -f "$ROOT/CLAUDE.md" && -f "${COMMAND_CONFIG_ROOT}/commands/commands.md" ]]; then
    printf '%s' "present"
  else
    printf '%s' "absent"
  fi
}

status_subagents() {
  if [[ -f "${COMMAND_CONFIG_ROOT}/_functions/collab/run-plan.md" ]] \
    && grep -Fq "execute-spawn" "${COMMAND_CONFIG_ROOT}/_functions/collab/run-plan.md"; then
    printf '%s' "present-narrowly"
  else
    printf '%s' "absent"
  fi
}

status_skills() {
  if has_public_commands && has_private_functions; then
    printf '%s' "present-conceptually"
  else
    printf '%s' "absent"
  fi
}

status_memory() {
  printf '%s' "absent - collab-scoped only"
}

assert_markers() {
  local begin_count end_count
  begin_count="$(grep -Fc "$BEGIN_MARKER" "$CONTRACT" || true)"
  end_count="$(grep -Fc "$END_MARKER" "$CONTRACT" || true)"
  [[ "$begin_count" == "1" ]] || die "expected exactly one begin marker in ${CONTRACT}"
  [[ "$end_count" == "1" ]] || die "expected exactly one end marker in ${CONTRACT}"
}

extract_existing_block() {
  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" '
    $0 == begin { in_block = 1; next }
    $0 == end { exit }
    in_block { print }
  ' "$CONTRACT"
}

row() {
  local primitive="$1" status="$2" notes="$3"
  printf '| %s | %s | %s |\n' "$primitive" "$status" "$notes"
}

generate_block() {
  printf '%s\n' "_Generated by \`tools/command-system/sync-framework-boundaries.sh\`; do not edit this block by hand._"
  printf '\n'
  printf '%s\n' "| Primitive | Status | Notes |"
  printf '%s\n' "| --- | --- | --- |"
  row "Instructions" "$(status_instructions)" "Bootstrap adapters, rules, and \`_core/\` docs define agent behavior."
  row "Workflows" "$(status_workflows)" "Public command routers and private \`_functions/\` playbooks own repeatable workflows."
  row "Repo-local tools" "$(status_repo_tools)" "\`tools/\` contains shell and Python helpers; this is distinct from AI function-calling and MCP tool servers."
  row "Adapters" "$(status_adapters)" "\`AGENTS.md\`, \`CLAUDE.md\`, and \`commands/commands.md\` keep agents routing-only."
  row "Subagents" "$(status_subagents)" "Only Completion-phase execution workers are in scope; they are not collab participants."
  row "Hooks" "absent - host-specific" "Document hooks per harness when needed; do not add them to the portable layer."
  row "Skills" "$(status_skills)" "Command namespaces behave like framework skills, but model-loaded skill packaging is out of scope."
  row "MCPs" "absent - out of scope by design" "MCP servers are host-native integrations, not portable framework primitives."
  row "Memory" "$(status_memory)" "The collab registry and transcripts are scoped state; cross-session memory is intentionally out of scope."
}

write_block() {
  local generated_file="$1" tmp_file
  tmp_file="$(mktemp)"
  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v generated="$generated_file" '
    $0 == begin {
      print
      while ((getline line < generated) > 0) {
        print line
      }
      in_block = 1
      next
    }
    $0 == end {
      in_block = 0
      print
      next
    }
    !in_block { print }
  ' "$CONTRACT" >"$tmp_file"
  mv "$tmp_file" "$CONTRACT"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      MODE="check"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
  shift
done

[[ -f "$CONTRACT" ]] || die "missing framework boundaries contract: $CONTRACT"
assert_markers

generated="$(mktemp)"
existing="$(mktemp)"
trap 'rm -f "$generated" "$existing"' EXIT

generate_block >"$generated"
extract_existing_block >"$existing"

if ! cmp -s "$generated" "$existing"; then
  if [[ "$MODE" == "check" ]]; then
    die "generated framework-boundary table is stale in ${CONTRACT}; run ./tools/command-system/sync-framework-boundaries.sh"
  fi
  write_block "$generated"
  echo "sync-framework-boundaries: updated ${CONTRACT}"
  exit 0
fi

if [[ "$MODE" == "check" ]]; then
  echo "sync-framework-boundaries: OK"
else
  echo "sync-framework-boundaries: already up to date"
fi
