#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
COMMAND_CONFIG_ROOT="${COMMAND_CONFIG_ROOT:-$ROOT}"
ROLES_DIR="${COMMAND_CONFIG_ROOT}/commands/collab/reference/roles"
ROLE_STANDARD_CONTRACT="${COMMAND_CONFIG_ROOT}/platform/standards/role-standard.md"
ROLES_SPEC_CONTRACT="${COMMAND_CONFIG_ROOT}/tests/specs/roles.md"
ROLE_STANDARD_BEGIN_MARKER="<!-- BEGIN GENERATED:ROLES_ROSTER -->"
ROLE_STANDARD_END_MARKER="<!-- END GENERATED:ROLES_ROSTER -->"
SPEC_TRACKED_BEGIN_MARKER="<!-- BEGIN GENERATED:TRACKED_ROSTER -->"
SPEC_TRACKED_END_MARKER="<!-- END GENERATED:TRACKED_ROSTER -->"
SPEC_JOINABLE_BEGIN_MARKER="<!-- BEGIN GENERATED:REQUIRED_ROSTER -->"
SPEC_JOINABLE_END_MARKER="<!-- END GENERATED:REQUIRED_ROSTER -->"
MODE="write"

die() {
  echo "sync-roles-roster: $*" >&2
  exit 1
}

usage() {
  cat <<'USAGE'
Usage: ./platform/tooling/sync-roles-roster.sh [--check]

Options:
  --check  Fail when generated role roster content is stale.
USAGE
}

assert_markers() {
  local contract="$1" begin_marker="$2" end_marker="$3" begin_count end_count
  begin_count="$(grep -Fc "$begin_marker" "$contract" || true)"
  end_count="$(grep -Fc "$end_marker" "$contract" || true)"
  [[ "$begin_count" == "1" ]] || die "expected exactly one begin marker in ${contract}"
  [[ "$end_count" == "1" ]] || die "expected exactly one end marker in ${contract}"
}

extract_existing_block() {
  local contract="$1" begin_marker="$2" end_marker="$3"
  awk -v begin="$begin_marker" -v end="$end_marker" '
    $0 == begin { in_block = 1; next }
    $0 == end { exit }
    in_block { print }
  ' "$contract"
}

generate_block() {
  printf '%s\n' "_Generated by \`platform/tooling/sync-roles-roster.sh\`; do not edit this block by hand._"
  printf '\n'
  printf '%s\n' "| Key | Display name |"
  printf '%s\n' "|-----|--------------|"
  python3 "$ROOT/platform/tooling/roles.py" --roles-dir "$ROLES_DIR" roster
}

generate_spec_roster_block() {
  local mode="$1"
  printf '%s\n' '<!-- shared-cmd-values exemption: registry-state mirror; role-key enumeration is generated output, not prose authorship. -->'
  printf '%s\n' "_Generated by \`platform/tooling/sync-roles-roster.sh\`; do not edit this block by hand._"
  printf '\n'
  python3 - "$ROLES_DIR" "$mode" <<'PY'
from __future__ import annotations

import json
import sys
from pathlib import Path

roles_dir = Path(sys.argv[1])
mode = sys.argv[2]

for path in sorted(roles_dir.glob("*.json")):
    if mode == "joinable":
        data = json.loads(path.read_text(encoding="utf-8"))
        if data.get("joinable", True) is False:
            continue
    print(f"- `{path.name}`")
PY
}

write_block() {
  local contract="$1" begin_marker="$2" end_marker="$3" generated_file="$4" tmp_file
  tmp_file="$(mktemp)"
  awk -v begin="$begin_marker" -v end="$end_marker" -v generated="$generated_file" '
    $0 == begin {
      print
      while ((getline line < generated) > 0) {
        print line
      }
      in_block = 1
      next
    }
    $0 == end {
      in_block = 0
      print
      next
    }
    !in_block { print }
  ' "$contract" >"$tmp_file"
  mv "$tmp_file" "$contract"
}

sync_block() {
  local label="$1" contract="$2" begin_marker="$3" end_marker="$4" generated_file="$5" existing_file="$6"
  extract_existing_block "$contract" "$begin_marker" "$end_marker" >"$existing_file"
  if cmp -s "$generated_file" "$existing_file"; then
    return 1
  fi
  if [[ "$MODE" == "check" ]]; then
    die "generated roster is stale in ${contract}; run ./platform/tooling/sync-roles-roster.sh"
  fi
  write_block "$contract" "$begin_marker" "$end_marker" "$generated_file"
  echo "sync-roles-roster: updated ${label} in ${contract}"
  return 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      MODE="check"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
  shift
done

[[ -f "$ROLE_STANDARD_CONTRACT" ]] || die "missing role contract: $ROLE_STANDARD_CONTRACT"
[[ -f "$ROLES_SPEC_CONTRACT" ]] || die "missing roles spec: $ROLES_SPEC_CONTRACT"
assert_markers "$ROLE_STANDARD_CONTRACT" "$ROLE_STANDARD_BEGIN_MARKER" "$ROLE_STANDARD_END_MARKER"
assert_markers "$ROLES_SPEC_CONTRACT" "$SPEC_TRACKED_BEGIN_MARKER" "$SPEC_TRACKED_END_MARKER"
assert_markers "$ROLES_SPEC_CONTRACT" "$SPEC_JOINABLE_BEGIN_MARKER" "$SPEC_JOINABLE_END_MARKER"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

standard_generated="$tmp_dir/standard-generated"
tracked_generated="$tmp_dir/tracked-generated"
joinable_generated="$tmp_dir/joinable-generated"
standard_existing="$tmp_dir/standard-existing"
tracked_existing="$tmp_dir/tracked-existing"
joinable_existing="$tmp_dir/joinable-existing"

generate_block >"$standard_generated"
generate_spec_roster_block tracked >"$tracked_generated"
generate_spec_roster_block joinable >"$joinable_generated"

updated=0
if sync_block "role standard roster" "$ROLE_STANDARD_CONTRACT" "$ROLE_STANDARD_BEGIN_MARKER" "$ROLE_STANDARD_END_MARKER" "$standard_generated" "$standard_existing"; then
  updated=1
fi
if sync_block "tracked QA roster" "$ROLES_SPEC_CONTRACT" "$SPEC_TRACKED_BEGIN_MARKER" "$SPEC_TRACKED_END_MARKER" "$tracked_generated" "$tracked_existing"; then
  updated=1
fi
if sync_block "joinable QA roster" "$ROLES_SPEC_CONTRACT" "$SPEC_JOINABLE_BEGIN_MARKER" "$SPEC_JOINABLE_END_MARKER" "$joinable_generated" "$joinable_existing"; then
  updated=1
fi

if [[ "$MODE" == "check" ]]; then
  echo "sync-roles-roster: OK"
elif [[ "$updated" == "1" ]]; then
  :
else
  echo "sync-roles-roster: already up to date"
fi
