#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
COMMAND_CONFIG_ROOT="${COMMAND_CONFIG_ROOT:-$ROOT}"
CATALOG="${COMMAND_CONFIG_ROOT}/commands/commands.md"
BEGIN_MARKER="<!-- BEGIN GENERATED:COMMANDS_ROSTER -->"
END_MARKER="<!-- END GENERATED:COMMANDS_ROSTER -->"
MODE="write"

die() {
  echo "sync-commands-catalog: $*" >&2
  exit 1
}

usage() {
  cat <<'USAGE'
Usage: ./platform/tooling/sync-commands-catalog.sh [--check]

Options:
  --check  Fail when generated roster content is stale.
USAGE
}

escape_table_cell() {
  sed 's/|/\\|/g'
}

dispatch_value() {
  local route_file="$1" dispatch
  dispatch="$(sed -n 's/^\*\*Dispatch:\*\* //p' "$route_file" | head -n 1)"
  if [[ "$dispatch" =~ \`([^\`]+)\` ]]; then
    dispatch="${BASH_REMATCH[1]}"
  fi
  printf '%s' "$dispatch"
}

route_label() {
  local route_file="$1" route route_slug slug_words dispatch inner token candidate
  local -a tokens candidate_tokens
  route_slug="$(basename "$(dirname "$route_file")")"
  slug_words="${route_slug//-/ }"
  dispatch="$(dispatch_value "$route_file")"
  if [[ "$dispatch" == \(*\) ]]; then
    inner="${dispatch#\(}"
    inner="${inner%\)}"
    tokens=()
    read -r -a tokens <<<"$inner"
    candidate_tokens=()
    for token in "${tokens[@]:1}"; do
      if [[ "$token" == \<* || "$token" == \[* || "$token" == --* || "$token" == *\<* ]]; then
        break
      fi
      candidate_tokens+=("$token")
    done
    candidate="${candidate_tokens[*]}"
    if [[ "$candidate" == "$route_slug" || "$candidate" == "$slug_words" ]]; then
      printf '%s' "$candidate"
    elif [[ "$candidate" == "$slug_words "* ]]; then
      printf '%s' "$slug_words"
    elif [[ -n "$candidate" ]]; then
      printf '%s' "$candidate"
    else
      printf '%s' "$slug_words"
    fi
    return
  fi
  route="$(basename "$(dirname "$route_file")")"
  route="${route//-/ }"
  printf '%s' "$route"
}

command_rel_path() {
  local command_file="$1" rel base
  rel="${command_file#"${COMMAND_CONFIG_ROOT}/commands/"}"
  base="$(basename "$command_file")"
  if [[ "$base" == "index.md" ]]; then
    printf '%s' "$rel"
  else
    printf '%s' "$base"
  fi
}

assert_markers() {
  local begin_count end_count
  begin_count="$(grep -Fc "$BEGIN_MARKER" "$CATALOG" || true)"
  end_count="$(grep -Fc "$END_MARKER" "$CATALOG" || true)"
  [[ "$begin_count" == "1" ]] || die "expected exactly one begin marker in ${CATALOG}"
  [[ "$end_count" == "1" ]] || die "expected exactly one end marker in ${CATALOG}"
}

extract_existing_block() {
  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" '
    $0 == begin { in_block = 1; next }
    $0 == end { exit }
    in_block { print }
  ' "$CATALOG"
}

generate_block() {
  local command_file rel base ns dispatch dispatch_cell public_link
  local route_file route_rel route route_dispatch route_link route_cell
  local command_route_label
  local route_links
  local -a namespace_routes route_entries command_files command_route_labels

  printf '%s\n' "_Generated by \`platform/tooling/sync-commands-catalog.sh\`; do not edit this block by hand._"
  printf '\n'
  printf '%s\n' "| Dispatch | Public router | Route playbooks |"
  printf '%s\n' "| --- | --- | --- |"

  command_files=()
  while IFS= read -r command_file; do
    command_files+=("$command_file")
  done < <(
    {
      find "${COMMAND_CONFIG_ROOT}/commands" -maxdepth 1 -type f -name '*.md'
      find "${COMMAND_CONFIG_ROOT}/commands" -mindepth 2 -maxdepth 2 -type f -name 'index.md'
    } | sort
  )

  for command_file in "${command_files[@]}"; do
    rel="$(command_rel_path "$command_file")"
    base="$(basename "$command_file")"
    [[ "$base" == "commands.md" ]] && continue
    [[ "$rel" == "index.md" ]] && continue

    if [[ "$base" == "index.md" ]]; then
      ns="$(basename "$(dirname "$command_file")")"
    else
      ns="${base%.md}"
    fi
    dispatch="$(dispatch_value "$command_file")"
    [[ -n "$dispatch" ]] || die "missing Dispatch label in $command_file"
    dispatch_cell="$(printf '%s' "$dispatch" | escape_table_cell)"
    public_link="[${ns}](${rel})"

    namespace_routes=()
    command_route_labels=()
    while IFS= read -r route_file; do
      command_route_labels+=("$(route_label "$route_file")")
    done < <(find "${COMMAND_CONFIG_ROOT}/commands/${ns}" -mindepth 2 -maxdepth 2 -type f -name 'index.md' 2>/dev/null | sort)
    while IFS= read -r route_file; do
      namespace_routes+=("$route_file")
    done < <(find "${COMMAND_CONFIG_ROOT}/commands/${ns}" -mindepth 2 -maxdepth 2 -type f -name 'index.md' 2>/dev/null | sort)

    if ((${#namespace_routes[@]} == 0)); then
      route_cell="n/a"
    else
      route_links=""
      for route_file in "${namespace_routes[@]}"; do
        route="$(route_label "$route_file")"
        route_rel="${route_file#"${COMMAND_CONFIG_ROOT}/commands/"}"
        route_link="[${route}](${route_rel})"
        if [[ -n "$route_links" ]]; then
          route_links="${route_links}, "
        fi
        route_links="${route_links}${route_link}"
      done
      route_cell="$route_links"
    fi

    printf "| \`%s\` | %s | %s |\n" "$dispatch_cell" "$public_link" "$route_cell"
  done

  printf '\n'
  printf '%s\n' "| Dispatch | Route playbook |"
  printf '%s\n' "| --- | --- |"
  route_entries=()
  while IFS= read -r route_file; do
    route_entries+=("$route_file")
  done < <(
    {
      find "${COMMAND_CONFIG_ROOT}/commands" -mindepth 3 -maxdepth 3 -type f -name 'index.md'
    } | sort
  )
  for route_file in "${route_entries[@]}"; do
    route_rel="${route_file#"${COMMAND_CONFIG_ROOT}/commands/"}"
    ns="$(dirname "$(dirname "$route_rel")")"
    route_link="[${route_rel}](${route_rel})"
    route="$(route_label "$route_file")"
    route_dispatch="$(dispatch_value "$route_file")"
    [[ -n "$route_dispatch" ]] || die "missing Dispatch label in $route_file"
    route_cell="$(printf '%s' "$route_dispatch" | escape_table_cell)"
    printf "| \`%s\` | %s |\n" "$route_cell" "$route_link"
  done
}

write_block() {
  local generated_file="$1" tmp_file
  tmp_file="$(mktemp)"
  awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v generated="$generated_file" '
    $0 == begin {
      print
      while ((getline line < generated) > 0) {
        print line
      }
      in_block = 1
      next
    }
    $0 == end {
      in_block = 0
      print
      next
    }
    !in_block { print }
  ' "$CATALOG" >"$tmp_file"
  mv "$tmp_file" "$CATALOG"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      MODE="check"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
  shift
done

[[ -f "$CATALOG" ]] || die "missing catalog: $CATALOG"
assert_markers

generated="$(mktemp)"
existing="$(mktemp)"
trap 'rm -f "$generated" "$existing"' EXIT

generate_block >"$generated"
extract_existing_block >"$existing"

if ! cmp -s "$generated" "$existing"; then
  if [[ "$MODE" == "check" ]]; then
    die "generated roster is stale in ${CATALOG}; run ./platform/tooling/sync-commands-catalog.sh"
  fi
  write_block "$generated"
  echo "sync-commands-catalog: updated ${CATALOG}"
  exit 0
fi

if [[ "$MODE" == "check" ]]; then
  echo "sync-commands-catalog: OK"
else
  echo "sync-commands-catalog: already up to date"
fi
